# ----- Github Action -----
name: Build and Deploy
# 実行のタイミング
on: workflow_dispatch
# on: [push]
# 実行の流れ
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Code
      - name: Checkout
        uses: actions/checkout@master
      # Install & Build
      - name: Install
        run: npm install
      - name: Build
        run: npm run generate
      # Deploy
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          # Branch: gh-pages
          target_branch: gh-pages
          build_dir: .output/public
